/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_BLE_PB_H_INCLUDED
#define PB_BLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BLEAdvertisingData {
    pb_callback_t name;
    pb_callback_t manufactureData;
    int32_t rssi;
} BLEAdvertisingData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BLEAdvertisingData_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define BLEAdvertisingData_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BLEAdvertisingData_name_tag              1
#define BLEAdvertisingData_manufactureData_tag   2
#define BLEAdvertisingData_rssi_tag              3

/* Struct field encoding specification for nanopb */
#define BLEAdvertisingData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    manufactureData,   2) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              3)
#define BLEAdvertisingData_CALLBACK pb_default_field_callback
#define BLEAdvertisingData_DEFAULT NULL

extern const pb_msgdesc_t BLEAdvertisingData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BLEAdvertisingData_fields &BLEAdvertisingData_msg

/* Maximum encoded size of messages (where known) */
/* BLEAdvertisingData_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
