/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_BLE_PB_H_INCLUDED
#define PB_BLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _WhiteListCommand {
    /* response with list */
    WhiteListCommand_REQUEST = 0
} WhiteListCommand;

typedef enum _WhiteListErrorCode {
    WhiteListErrorCode_OK = 0,
    WhiteListErrorCode_NULL = 1,
    WhiteListErrorCode_OUT_OF_MEMORY = 2
} WhiteListErrorCode;

/* Struct definitions */
typedef struct _WhiteItem {
    pb_size_t which_item;
    union {
        /* name is a regex */
        pb_callback_t name;
        pb_callback_t mac;
    } item;
} WhiteItem;

typedef struct _WhiteList {
    pb_callback_t items;
} WhiteList;

typedef struct _WhiteListRequest {
    pb_size_t which_request;
    union {
        WhiteListCommand command;
        WhiteList set;
    } request;
} WhiteListRequest;

typedef struct _WhiteListResponse {
    pb_size_t which_response;
    union {
        WhiteList list;
        WhiteListErrorCode code;
    } response;
} WhiteListResponse;


/* Helper constants for enums */
#define _WhiteListCommand_MIN WhiteListCommand_REQUEST
#define _WhiteListCommand_MAX WhiteListCommand_REQUEST
#define _WhiteListCommand_ARRAYSIZE ((WhiteListCommand)(WhiteListCommand_REQUEST+1))

#define _WhiteListErrorCode_MIN WhiteListErrorCode_OK
#define _WhiteListErrorCode_MAX WhiteListErrorCode_OUT_OF_MEMORY
#define _WhiteListErrorCode_ARRAYSIZE ((WhiteListErrorCode)(WhiteListErrorCode_OUT_OF_MEMORY+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WhiteItem_init_default                   {0, {{{NULL}, NULL}}}
#define WhiteList_init_default                   {{{NULL}, NULL}}
#define WhiteListResponse_init_default           {0, {WhiteList_init_default}}
#define WhiteListRequest_init_default            {0, {_WhiteListCommand_MIN}}
#define WhiteItem_init_zero                      {0, {{{NULL}, NULL}}}
#define WhiteList_init_zero                      {{{NULL}, NULL}}
#define WhiteListResponse_init_zero              {0, {WhiteList_init_zero}}
#define WhiteListRequest_init_zero               {0, {_WhiteListCommand_MIN}}

/* Field tags (for use in manual encoding/decoding) */
#define WhiteItem_name_tag                       1
#define WhiteItem_mac_tag                        2
#define WhiteList_items_tag                      1
#define WhiteListRequest_command_tag             1
#define WhiteListRequest_set_tag                 2
#define WhiteListResponse_list_tag               1
#define WhiteListResponse_code_tag               2

/* Struct field encoding specification for nanopb */
#define WhiteItem_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (item,name,item.name),   1) \
X(a, CALLBACK, ONEOF,    BYTES,    (item,mac,item.mac),   2)
#define WhiteItem_CALLBACK pb_default_field_callback
#define WhiteItem_DEFAULT NULL

#define WhiteList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define WhiteList_CALLBACK pb_default_field_callback
#define WhiteList_DEFAULT NULL
#define WhiteList_items_MSGTYPE WhiteItem

#define WhiteListResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,list,response.list),   1) \
X(a, STATIC,   ONEOF,    UENUM,    (response,code,response.code),   2)
#define WhiteListResponse_CALLBACK NULL
#define WhiteListResponse_DEFAULT NULL
#define WhiteListResponse_response_list_MSGTYPE WhiteList

#define WhiteListRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (request,command,request.command),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set,request.set),   2)
#define WhiteListRequest_CALLBACK NULL
#define WhiteListRequest_DEFAULT NULL
#define WhiteListRequest_request_set_MSGTYPE WhiteList

extern const pb_msgdesc_t WhiteItem_msg;
extern const pb_msgdesc_t WhiteList_msg;
extern const pb_msgdesc_t WhiteListResponse_msg;
extern const pb_msgdesc_t WhiteListRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WhiteItem_fields &WhiteItem_msg
#define WhiteList_fields &WhiteList_msg
#define WhiteListResponse_fields &WhiteListResponse_msg
#define WhiteListRequest_fields &WhiteListRequest_msg

/* Maximum encoded size of messages (where known) */
/* WhiteItem_size depends on runtime parameters */
/* WhiteList_size depends on runtime parameters */
/* WhiteListResponse_size depends on runtime parameters */
/* WhiteListRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
