/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "track_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Color, Color, AUTO)


PB_BIND(TrackData, TrackData, AUTO)


PB_BIND(TrackData_PaceEntry, TrackData_PaceEntry, AUTO)


PB_BIND(TrackConfig, TrackConfig, AUTO)


PB_BIND(TrackState, TrackState, AUTO)


PB_BIND(TrackStates, TrackStates, AUTO)


PB_BIND(TrackStatusMsg, TrackStatusMsg, AUTO)

