/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "track_option.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MaxLed, MaxLed, AUTO)


PB_BIND(CountLed, CountLed, AUTO)


PB_BIND(CircleLength, CircleLength, AUTO)


PB_BIND(TrackOptions, TrackOptions, AUTO)



