/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "track_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Color, Color, AUTO)


PB_BIND(TupleIntFloat, TupleIntFloat, AUTO)


PB_BIND(TrackConfig, TrackConfig, AUTO)


PB_BIND(TrackState, TrackState, AUTO)


PB_BIND(TrackStates, TrackStates, AUTO)




