name: ESP-IDF CMake Build

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "idf-v4.4.5" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.5
          target: esp32
          path: '.'

      # Upload Artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: |
            build/*.bin
            build/*.elf
            build/*.map
